export const localityMapping = {
  " Vibhutipura. Tata Sherwood Road.Bengaluru, Karnataka 560037": 0,
  "#11, Lavnya apartment, 2nd main, 2nd Cross nagaraj layout, kaveryappa layout, Kaverappa Layout, Kadubeesanahalli, Bengaluru, Karnataka 560103, India,Bengaluru": 1,
  ", Hoodi": 2,
  "10th B Cross Road,Bengaluru": 3,
  "112, 2nd Cross Rd, Sri Nivasa Reddy Layout, AECS Layout, Marathahalli, Bengaluru, Karnataka 560037, India,Bengaluru": 4,
  "124, 1st Cross Rd, Bharathi Layout, Venkateshwara Layout, Suddagunte Palya, Bengaluru, Karnataka 560029, India,Bengaluru": 5,
  "12th Cross, Kalappa Layout, Rasanna Colony, Vibhutipura, Bengaluru, Karnataka 560037, India,Bengaluru": 6,
  "13th Cross, Manjunatha Layout, Munnekollal, Bengaluru, Karnataka 560037, India,Bengaluru": 7,
  "141, 7th Cross Road, Stage 2, Hoysala Nagar, Indiranagar, Bengaluru, Karnataka 560038, India,Bengaluru": 8,
  "165, 22nd Main Rd, Lakshmi Layout, MCHS Colony, Stage 2, BTM Layout, Bengaluru, Karnataka 560076, India,Bengaluru": 9,
  "183, 4th Main Road, Maithri Layout, Kadugodi": 10,
  "1st Block Koramangala": 11,
  "1st Block Koramangala,HSR Layout 5th Sector": 12,
  "1st Phase JP Nagar": 13,
  "1st Phase, JP Nagar": 14,
  "1st Phase,JP Nagar": 15,
  "1st Sector, HSR Layout": 16,
  "1st Sector, HSR Layout, Bengaluru, Karnataka, India": 17,
  "1st Sector,HSR Layout": 18,
  "1st Stage, BTM Layout": 19,
  "1st Stage, BTM Layout 1": 20,
  "1st Stage,BTM Layout": 21,
  "1st Stage,BTM Layout 1": 22,
  "2A Cross Road, Rajasree Layout, Gandhi Nagar, Munnekollal": 23,
  "2nd Phase JP Nagar": 24,
  "2nd Phase, JP Nagar": 25,
  "2nd Phase, JP Nagar,": 26,
  "3, Kathriguppa Main Rd, ITI Layout, Banashankari 3rd Stage, Banashankari": 27,
  "377, 11th Main Rd, Teacher&#39;s Colony, Jakkasandra, Sector 7, HSR Layout, Bengaluru, Karnataka 560034, India,Bengaluru": 28,
  "3G Homes Crimson Layout,Kadugodi": 29,
  "3rd Phase, JP Nagar": 30,
  "45, 1st A Main Road,Bengaluru": 31,
  "529 12th main 9th cross bsk 3rd stage": 32,
  "5th Phase, J P Nagar Phase 5,": 33,
  "5th Phase, JP Nagar": 34,
  "6th Block, Bellandur": 35,
  "6th Block,Koramangala": 36,
  "9th Block Jayanagara, Jayanagar, Bengaluru, Karnataka, India": 37,
  "AECS Layout": 38,
  "AECS Layout - C Block": 39,
  "AECS Layout, Kundalahalli, Brookefield, Bengaluru, Karnataka, India": 40,
  "AECS Layout, Marathahalli": 41,
  "AECS Layout, Marathahalli, Bengaluru, Karnataka, India": 42,
  "AECS Layout,Marathahalli": 43,
  "AGS layout next to poornapragna layout": 44,
  "AK Colony,Adugodi": 45,
  "Adarsh Palm Retreat, Bellandur": 46,
  "Adarsh Palm Retreat,Bellandur": 47,
  "Adithya Elan, New Temple Road, Nallurhalli, Whitefield, Bengaluru, Karnataka, India": 48,
  Adugodi: 49,
  Adyar: 50,
  Agram: 51,
  "Ags Layout, Banashankari, Bengaluru, Karnataka, India": 52,
  "Akash Nagar, A Narayanpura": 53,
  "Akshara Aspire, Vijay Nagar, Whitefield, Bengaluru, Karnataka 560066, India,Bengaluru": 54,
  "Amarajyothi Nagar": 55,
  "Amarjyothi Layout, Domlur": 56,
  "Amarjyoti Layout,Domlur": 57,
  Ambalipura: 58,
  "Ambalipura Residency Road, PWD Quarters, Bengaluru, Karnataka, India": 59,
  "Ambalipura,Harlur": 60,
  "Ambedkar Nagar,Whitefield": 61,
  Amblipura: 62,
  "Annapoorneshwari Nagar": 63,
  "Annapurneshwari Nagar": 64,
  "Annasandra Palya": 65,
  Annasandrapalya: 66,
  "Annasandrapalya Extension": 67,
  "Anubhav Nagar": 68,
  "Arehalli, Bengaluru, Karnataka, India": 69,
  "Ashok Nagar": 70,
  "Ashwini layout": 71,
  Attiguppe: 72,
  "Austin Town": 73,
  "Ayyappa Nagar,Krishnarajapura": 74,
  "B Narayanapura": 75,
  "B Narayanapura, Mahadevapura": 76,
  "B Narayanapura,Mahadevapura": 77,
  "BEML Layout": 78,
  "BHEL Layout": 79,
  "BSK 2nd Stage": 80,
  "BSK 3rd Stage": 81,
  "BSK 3rd Stage, Bengaluru, Karnataka, India": 82,
  "BSK II Stage": 83,
  BTM: 84,
  "BTM 1st Stage": 85,
  "BTM 2nd Stage": 86,
  "BTM 2nd Stage,": 87,
  "BTM 2nd Stage, Bengaluru, Karnataka, India": 88,
  "BTM Layout": 89,
  "BTM Layout 1": 90,
  "BTM Layout 1st Stage": 91,
  "BTM Layout 2nd Stage": 92,
  "BTM Layout 2nd Stage, Bengaluru, Karnataka, India": 93,
  "BTM Layout Stage 2": 94,
  "BTM Layout,": 95,
  "BTM Layout, 1st Stage": 96,
  "BTM Layout, Bengaluru, Karnataka, India": 97,
  Balagere: 98,
  "Balagere Road, Lords Steps layout, Balagere": 99,
  "Balagere, Bengaluru, Karnataka, India": 100,
  Banagirinagara: 101,
  Banashankari: 102,
  "Banashankari 2nd Stage": 103,
  "Banashankari 3rd Stage": 104,
  "Banashankari 3rd Stage,": 105,
  "Banashankari 3rd Stage, Banashankari": 106,
  "Banashankari 3rd Stage, Banashankari, Bengaluru, Karnataka, India": 107,
  "Banashankari 3rd Stage, Hosakerehalli": 108,
  "Banashankari 3rd Stage, No 32 Dsouza nagar behind pesit": 109,
  "Banashankari 3rd Stage,Banashankari": 110,
  "Banashankari Stage 1": 111,
  "Banashankari Stage I": 112,
  "Banashankari Stage I,Banashankari": 113,
  "Banashankari Stage II": 114,
  "Banashankari Stage II, Banashankari": 115,
  "Banashankari Stage II, Banashankari, Bengaluru, Karnataka 560070, India": 116,
  "Banashankari Temple Ward": 117,
  "Banashankari, Bengaluru, Karnataka, India": 118,
  Banashankri: 119,
  Banaswadi: 120,
  "Bapuji Nagar": 121,
  Basavanagar: 122,
  Basavanagara: 123,
  Basavanagudi: 124,
  "Basavanagudi, Bengaluru, Karnataka, India": 125,
  "Basavanna Nagar": 126,
  "Basaveshvara Nagar": 127,
  "Basaveshwar Nagar": 128,
  "Basaveshwar Nagar,": 129,
  "Basaveshwara Nagar": 130,
  Basaveshwaranagar: 131,
  "Basaweshwara Nagar": 132,
  Battarahalli: 133,
  "Belatur Colony,Brindavan Layout": 134,
  Bellandur: 135,
  "Bellandur junction, Bellandur Flyover, Adarsh Palm Retreat, Bellandur, Bengaluru, Karnataka 560103, India,Bengaluru": 136,
  "Bellandur, Bengaluru, Karnataka, India": 137,
  "Bennigana Halli": 138,
  "Benson Town": 139,
  "Bharath Housing Society Layout,Banashankari": 140,
  Bhoganhalli: 141,
  "Bhoganhalli, Bengaluru, Karnataka, India": 142,
  "Bhoganhalli, post: Bellandur, Bengaluru, Karnataka, India": 143,
  "Bhuvaneshwari Nagar": 144,
  Bilekahalli: 145,
  Billekahalli: 146,
  "Binny Mills Employees Colony,JP Nagar": 147,
  Bismillahnagar: 148,
  Bommanahalli: 149,
  "Bommanahalli, Bengaluru, Karnataka, India": 150,
  Brookefield: 151,
  "Brookefield, Bengaluru, Karnataka, India": 152,
  Brookfield: 153,
  Byappanahalli: 154,
  Byatarayanapura: 155,
  Byrasandra: 156,
  "C V Raman": 157,
  "C V Raman Nagar": 158,
  "CHANDRA LAYOUT": 159,
  "CV Raman Nagar": 160,
  "Cambridge Layout": 161,
  Carmelaram: 162,
  "Carmelaram, Bengaluru, Karnataka, India": 163,
  "Cauvery Colony,Koramangala": 164,
  "Chakravarthy Layout": 165,
  Challaghatta: 166,
  Chamarajpet: 167,
  Chamrajpet: 168,
  "Chandana,": 169,
  "Chandra Layout": 170,
  "Chandra Layout,Marathahalli": 171,
  Channasandra: 172,
  "Channasandra,Srinivaspura": 173,
  Chansandra: 174,
  "Chansandra, Koralur": 175,
  "Chennappa Layout,Chinnapanna Halli": 176,
  Chickpet: 177,
  "Chikka Adugodi": 178,
  "Chikka Madivala": 179,
  Chikkabellandur: 180,
  Chikkakannalli: 181,
  Chikkalasandra: 182,
  Chikkalsandra: 183,
  Chikkasandra: 184,
  "Chikku Lakshmaiah Layout,Adugodi": 185,
  "Chinappa Layout,Mahadevapura": 186,
  Chinnapanahalli: 187,
  "Chinnapanna Halli": 188,
  Cholourpalya: 189,
  "Cleveland Town": 190,
  "Cooke Town": 191,
  Cottonpete: 192,
  "Cox Town": 193,
  "Cox Town, Bengaluru, Karnataka, India": 194,
  "Creative Sree Nilaya, HSR Layout, Bengaluru, Karnataka, India": 195,
  Cubbonpete: 196,
  "Dairy Circle": 197,
  Dasarahalli: 198,
  "Dattatreya Nagar": 199,
  "Deepanjali Nagar": 200,
  "Defence Scientist": 201,
  "Devarabeesana Halli": 202,
  "Devarabisanahalli,Bellandur": 203,
  "Devasthanagalu,Balagere": 204,
  "Devasthanagalu,Varthur": 205,
  "DivyaSree Republic of Whitefield, Kundalahalli Rd, Kundalahalli, Whitefield, Bengaluru, Karnataka, India": 206,
  "Dodda Banaswadi": 207,
  "Dodda Nekkundi Extension,Doddanekkundi": 208,
  DoddaNekkundi: 209,
  Doddakannalli: 210,
  Doddakannelli: 211,
  "Doddakannelli, Bengaluru, Karnataka, India": 212,
  Doddanakundi: 213,
  Doddanekkundi: 214,
  "Doddanekkundi Industrial Area Road, Dodda Nekkundi Extension, Doddanekkundi, Bengaluru, Karnataka, India": 215,
  "Doddanekkundi,": 216,
  "Doddanekkundi,Doddanekkundi": 217,
  Doddanekundi: 218,
  "Doddanekundi,Doddanekkundi": 219,
  "Doddanekundi,Kaggadasapura": 220,
  "Doddanekundi,Mahadevapura": 221,
  "Dodsworth Layout,Whitefield": 222,
  Domlur: 223,
  Doopanahalli: 224,
  "Dwaraka Nagar,Banashankari": 225,
  "EPIP Zone,Brookefield": 226,
  "EPIP Zone,Whitefield": 227,
  "Eastwood Township,Harlur": 228,
  "Eastwood Township,Kasavanahalli": 229,
  "Edgah Road, Devasthanagalu, Varthur": 230,
  Egipura: 231,
  Ejipura: 232,
  "Ejipura,": 233,
  "Ejipura, Bengaluru, Karnataka, India": 234,
  "Eshwara Layout,Indiranagar": 235,
  "Excel Stone Florence Apartments, Balagere, Bengaluru, Karnataka, India": 236,
  "Food Garden Road, Food Garden Rd, Anugraha Layout, Langford Town, Shanti Nagar, Bengaluru, Karnataka 560027, India": 237,
  "Frazer Town": 238,
  "GM Palya": 239,
  "GM Palya, C V Raman Nagar, Bengaluru, Karnataka, India": 240,
  "GM Palya,C V Raman Nagar": 241,
  "Gandhi Bazaar": 242,
  "Gandhi Nagar, Munnekollal": 243,
  "Gandhi Nagar,Marathahalli": 244,
  "Ganesh Nivas, 7th Cross Road, Ramanjaneyanagar, Bengaluru, Karnataka, India": 245,
  Garebhavipalya: 246,
  "Garudachar Palya, Mahadevapura": 247,
  "Garudachar Palya,Mahadevapura": 248,
  "Gattigere,RR Nagar": 249,
  "Giri Nagar": 250,
  Girinagar: 251,
  "Girinagar, Banashankari": 252,
  "Global village Tech Park Road, RV Vidyaniketan, Bengaluru, Karnataka, India": 253,
  "Gnana Bharathi": 254,
  "Govindaraja Nagar Ward, Govindarajanagar, Vijaya Nagar, Bengaluru, Karnataka, India": 255,
  Govindarajanaga: 256,
  Govindarajanagar: 257,
  "Green Glen Layout": 258,
  "Green Glen Layout, Bellandur": 259,
  "Green Glen Layout,Bellandur": 260,
  Guddadahalli: 261,
  Gunjur: 262,
  "Gunjur Palya": 263,
  "Gunjur Village": 264,
  "Gunjur, Bengaluru, Karnataka, India": 265,
  Guttahalli: 266,
  HAL: 267,
  "HAL 2nd Stage": 268,
  "HAL 3rd Stage": 269,
  "HAL 3rd Stage, Bengaluru, Karnataka, India": 270,
  "HAL Post": 271,
  HARLUR: 272,
  "HSR Layout": 273,
  "HSR Layout 1st Sector": 274,
  "HSR Layout 2nd Sector": 275,
  "HSR Layout 5th Sector": 276,
  "HSR Layout 7th Sector": 277,
  "HSR Layout Sector 7": 278,
  "HSR Layout,": 279,
  "HSR Layout, Sector 1": 280,
  "HSR Layout, Sector 3": 281,
  "HSR Layout, Sector 7": 282,
  "HSR layout": 283,
  "HSR layout Sector 2": 284,
  Halanayakanahalli: 285,
  Halasahalli: 286,
  Halasuru: 287,
  "Halasuru Police Station": 288,
  "Hampi Nagar": 289,
  "Hanumanth Nagar": 290,
  "Hanumanth Nagar, Near Ramanjaneya Temple": 291,
  Hanumanthnagar: 292,
  Haralur: 293,
  Harlur: 294,
  "Harlur Main Road": 295,
  "Harlur Main Road, PWD Quarters, 1st Sector, Harlur, Bengaluru, Karnataka, India": 296,
  "Hemmigepura Ward 198,RR Nagar": 297,
  Hombegowda: 298,
  Hongasandra: 299,
  Hoodi: 300,
  "Hoodi Circle, Hudi, Hoodi, Bengaluru, Karnataka": 301,
  "Hoodi Railway Flyover, Thigalarapalya, Krishnarajapura,": 302,
  "Hope Farm Junction, Maithri Layout, Kadugodi, Bengaluru, Karnataka": 303,
  "Hope Farm, Maithri Layout, Kadugodi, Bengaluru, Karnataka, India": 304,
  Hosakerehalli: 305,
  Hosapalaya: 306,
  "ISRO Layout": 307,
  "ITC Colony,Maruthi Sevanagar": 308,
  "ITI Layout": 309,
  "ITI Layout, Sector 7": 310,
  ITPL: 311,
  "ITPL, Whitefield, Bengaluru, Karnataka, India": 312,
  Ibblur: 313,
  "Iblur Village": 314,
  "Iblur Village,Bellandur": 315,
  "Ideal Homes Township,RR Nagar": 316,
  "Ilyas Nagar,Kumaraswamy Layout": 317,
  Immadihalli: 318,
  "Immadihalli, Whitefield": 319,
  "Immadihalli,Whitefield": 320,
  "India Post, HAL 3rd Stage, Bhoomi Reddy Colony, New Tippasandra, Bengaluru, Karnataka, India": 321,
  "Indira Nagar": 322,
  "Indira Nagar II Stage": 323,
  "Indira Nagar II Stage, Hoysala Nagar, Indiranagar, Bengaluru, Karnataka, India": 324,
  Indiranagar: 325,
  Indiranagar6: 326,
  "Industrial Area,Hoodi": 327,
  "Islampur,Vibhutipura": 328,
  Ittamadu: 329,
  "J P Nagar": 330,
  "J P Nagar 5 Phase": 331,
  "J P Nagar 5th Phase": 332,
  "J P Nagar Phase 5": 333,
  "J P Nagar Phase 5,JP Nagar": 334,
  "J. P. Nagar": 335,
  "JCR Layout,Panathur": 336,
  "JP Nagar": 337,
  "JP Nagar 1st Phase": 338,
  "JP Nagar 4th Phase": 339,
  "JP Nagar 5th Phase": 340,
  "JP Nagar 7th Phase": 341,
  "JP Nagar Phase 2": 342,
  "JP Nagar Phase 6": 343,
  "JP Nagar Phase 6,": 344,
  "JP Nagar Phase 6, JP Nagar, Bengaluru, Karnataka, India": 345,
  "JP Nagar Phase 6,JP Nagar": 346,
  "JP Nagar,": 347,
  "JP Nagar, 2nd Phase": 348,
  "Jagadish Nagar": 349,
  "Jagadish Nagar, Basaweshwar Nagar, Nelluru Puram, Kaggadasapura, Bengaluru, Karnataka, India": 350,
  "Jagadish Nagar,Kaggadasapura": 351,
  "Jai Bheema Nagar": 352,
  Jakkasandra: 353,
  "Janatha Colony,Chikkabellandur": 354,
  "Jaya Nagar": 355,
  "Jaya Nagar 9th Block": 356,
  "Jaya Nagar 9th Block, 25th Main Road, Jayanagara 9th Block, Bengaluru, Karnataka, India": 357,
  "Jaya Nagar East": 358,
  "Jaya Nagar East,Jayanagar": 359,
  Jayamahal: 360,
  Jayanagar: 361,
  "Jayanagar 1st Block": 362,
  "Jayanagar 2nd Block": 363,
  "Jayanagar 3rd Block": 364,
  "Jayanagar 3rd Block East": 365,
  "Jayanagar 4 Block": 366,
  "Jayanagar 5th block": 367,
  "Jayanagar 7 Block": 368,
  "Jayanagar 9 block": 369,
  Jayanagara: 370,
  "Jayanagara 9th Block": 371,
  "Jayaprakash Nagar Metro Station, Kanakapura Road, Ilyas Nagar, Banashankari Temple Ward, Bengaluru, Karnataka, India": 372,
  "Jeevan Bhima Nagar": 373,
  "Jeevan Bima Nagar": 374,
  "Jeevan Samskruthi Apartment, Shiridi Sai Temple Rd., 4th A Cross, Shirdi Sai Nagar, Munnekollal, Bengaluru, Karnataka 560037, India,Bengaluru": 375,
  Jeevanahalli: 376,
  Jeevanhalli: 377,
  Jogupalya: 378,
  Junnasandra: 379,
  "Jyothi Nagar": 380,
  "Jyothi Puram,Dooravani Nagar": 381,
  "K R Garden,Murgesh Pallya": 382,
  "KEB Rd, Chikka Madivala, 1st Stage, BTM Layout 1, Bengaluru, Karnataka 560068, India,Bengaluru": 383,
  "KHB Games Village,Koramangala": 384,
  "KPC Layout": 385,
  "KR Garden, Murgesh Pallya": 386,
  "KR Market": 387,
  Kachamaranahalli: 388,
  Kadarenahalli: 389,
  Kadubeesanahalli: 390,
  "Kadubeesanahalli,": 391,
  "Kadubeesanahalli, Bengaluru, Karnataka, India": 392,
  Kadugodi: 393,
  "Kadugodi, Bengaluru, Karnataka, India": 394,
  Kaggadasapura: 395,
  "Kaggadasapura, Bengaluru, Karnataka, India": 396,
  Kaikondanarhalli: 397,
  Kaikondrahalli: 398,
  Kalasipalya: 399,
  "Kalidasa Layout, Srinagar, Banashankari, Bengaluru, Karnataka, India": 400,
  "Kalyan Nagar": 401,
  "Kamadhenu Nagar": 402,
  Kamaksipalya: 403,
  "Kamala Nagar, Bengaluru, Karnataka, India": 404,
  "Kamanahalli, Bengaluru, Karnataka, India": 405,
  "Kamaraj Road, FM Cariappa Colony, Bengaluru, Karnataka, India": 406,
  Kammanahalli: 407,
  "Kariyammana Agrahara,Bellandur": 408,
  Kasavanahalli: 409,
  "Kasavanahalli Off Sarjapur Road": 410,
  "Kasavanahalli, Bengaluru, Karnataka 560035, India": 411,
  "Kasavanahalli, Bengaluru, Karnataka, India": 412,
  Kasavanhalli: 413,
  Kathreguppe: 414,
  Kathriguppe: 415,
  "Kathriguppe, Banashankari 3rd Stage, Banashankari, Bengaluru, Karnataka, India": 416,
  "Kaveri Layout": 417,
  "Kaveri Nagar,Krishnarajapura": 418,
  "Kempapura Agrahara": 419,
  "Kempegowda Layout": 420,
  "Kempegowda Nagar": 421,
  "Kenchenhalli,RR Nagar": 422,
  Kengunte: 423,
  "Keshava Nagar": 424,
  "Keshava Nagar,Binnipete": 425,
  Kodbisanhalli: 426,
  "Kodbisanhalli,": 427,
  Kodichikkanahalli: 428,
  "Kodichikknahalli, Bengaluru, Karnataka, India": 429,
  Kodigehalli: 430,
  "Kodigehalli,Krishnarajapura": 431,
  Kodihalli: 432,
  "Kodihalli, HAL 3rd Stage": 433,
  Konanakunte: 434,
  "Konena Agrahara": 435,
  Koralur: 436,
  Koramanagala: 437,
  Koramangala: 438,
  "Koramangala 3 Block": 439,
  "Koramangala 4 Block": 440,
  "Koramangala 4th Block, Koramangala, Bengaluru, Karnataka, India": 441,
  "Koramangala 4th Block,HSR Layout 5th Sector": 442,
  "Koramangala 6th Block": 443,
  "Koramangala 7th Block": 444,
  "Koramangala 8th Block": 445,
  "Koramangala 8th Block, Koramangala, Bengaluru, Karnataka, India": 446,
  "Koramangala, Bengaluru, Karnataka, India": 447,
  Kormangala: 448,
  "Kormangala 2nd block": 449,
  "Krishna Garden Road, RR Nagar, Bengaluru, Karnataka, India": 450,
  "Krishnappa Garden,Krishnarajapura": 451,
  Krishnarajapura: 452,
  Krishnarajapuram: 453,
  "Kumara Park West": 454,
  "Kumarapark West": 455,
  "Kumaraswamy Layout": 456,
  "Kumaraswamy Layout II Stage": 457,
  Kundalahalli: 458,
  "Kundalahalli Colony,Brookefield": 459,
  "Kundalahalli Gate": 460,
  "Kundalahalli Gate, Varthur Main Road, Brookefield, Bengaluru, Karnataka, India": 461,
  "Kundalahalli, Bengaluru, Karnataka, India": 462,
  "Kundalahalli,Brookefield": 463,
  "Kundalahalli,Whitefield": 464,
  "Kundanahalli Gate": 465,
  "LB Shastri Nagar": 466,
  "LBS Nagar": 467,
  "LBS Nagar, Vimanapura": 468,
  "LBS Nagar,Vimanapura": 469,
  Lakkasandra: 470,
  Lakshminarayanapuram: 471,
  "Lal Bahadur Shastri Nagar": 472,
  Laljinagar: 473,
  "Langford Gardens": 474,
  "Langford Town": 475,
  "Langford Town, Shanti Nagar, Bengaluru": 476,
  "Leela Palace Road, HAL 3rd Stage, Kodihalli": 477,
  "Lingayana Palya": 478,
  "M.C.Layout, Vijayanagar": 479,
  Madambakkam: 480,
  "Madhura Nagar": 481,
  "Madhura Nagar, Bengaluru, Karnataka, India": 482,
  Madiwala: 483,
  Mahadevapura: 484,
  "Mahadevapura,": 485,
  Mahadevpura: 486,
  Mailasandra: 487,
  "Maithri Layout,Kadugodi": 488,
  Mallathahalli: 489,
  Malleshpalya: 490,
  "Malleshpalya, Kaggadasapura": 491,
  "Malleshpalya,C V Raman Nagar": 492,
  "Malleshpalya,Kaggadasapura": 493,
  Malleshwaram: 494,
  "Malleshwaram West": 495,
  Malleswaram: 496,
  Mangammanapalya: 497,
  "Manjunatha Nagar": 498,
  Marathahalli: 499,
  "Marathahalli Village,Marathahalli": 500,
  "Marathahalli, Bengaluru, Karnataka, India": 501,
  "Maruthi Nagar": 502,
  "Maruthi Sevanagar": 503,
  "Maruti Nagar": 504,
  Mavalli: 505,
  Meenambakkam: 506,
  "Michael Palaya": 507,
  "Mico Layout": 508,
  Moodalapalya: 509,
  Mudalapalya: 510,
  "Mudalapalya, Vijaya Nagar": 511,
  Mullur: 512,
  Munekollal: 513,
  "Muneshwara Block": 514,
  "Muneshwara Block, Telecom Colony, Bengaluru, Karnataka, India": 515,
  "Muneshwara Nagar": 516,
  "Muneswara Block": 517,
  "Munivenkatppa Layout,Bilekahalli": 518,
  Munnekolal: 519,
  Munnekollal: 520,
  "Munnekollal, Bengaluru, Karnataka, India": 521,
  Munnekollalu: 522,
  "Munnireddy Layout, Panathur": 523,
  "Munnireddy Layout,Panathur": 524,
  "Murgesh Pallya": 525,
  Murgeshpalya: 526,
  "Murphy Town,Ulsoor": 527,
  Murugeshpalya: 528,
  "NGEF Layout": 529,
  "NGEF Layout Nagarabhavi, NGEF Layout, Stage 2,": 530,
  "NGR Layout,Bommanahalli": 531,
  "NS Palya": 532,
  "Nagappa Block": 533,
  Nagapura: 534,
  Nagarabhavi: 535,
  "Nagarabhavi 2nd Stage": 536,
  "Nagarabhavi Circle": 537,
  Nagarathpete: 538,
  Nagarbhavi: 539,
  "Nagarbhavi 1st Stage, Stage 2, Chandra Layout, Bengaluru, Karnataka, India": 540,
  "Nagarbhavi 2nd Stage": 541,
  "Nagarbhavi Circle, Nagarabhavi Circle, Jyothi Nagar, Bengaluru, Karnataka, India": 542,
  "Nagarbhavi, Bengaluru, Karnataka, India": 543,
  Nagavarapalya: 544,
  Nagondanahalli: 545,
  Nallurhalli: 546,
  "Nallurhalli, Whitefield, Bengaluru, Karnataka, India": 547,
  "Nallurhalli,Whitefield": 548,
  "Narayanappa Garden,Whitefield": 549,
  Narayanapura: 550,
  "Nayanda Halli": 551,
  "Near Gopalan Arcade Mall, Behind Jain College,IRR Nagar,": 552,
  Neelasandra: 553,
  "Nelluru Puram": 554,
  "New Baiyyappanahalli Extension": 555,
  "New Guddadahalli": 556,
  "New Thippasandra": 557,
  "New Timberyard Layout": 558,
  "New Tippasandra": 559,
  "No 8215,4th Main,2nd Cross,Shanthinikethan Layout, Marathahalli, 4, SGR Dental College Rd, Shamanna Reddy Layout, Kasavanahalli Village, Bellandur, Bengaluru, Karnataka 560037, India,Bengaluru": 560,
  "No. 99, 8th A Cross Road, 3rd Main, Venkatapura, Koramangala 1st Block, Teacher&#39;s Colony, Jakkasandra, 1st Block Koramangala, HSR Layout 5th Sector, Bengaluru, Karnataka 560034, India,Bengaluru": 561,
  "Outer Ring Road, Mahadevapura, Bengaluru, Karnataka, India": 562,
  "Padmanabha Nagar": 563,
  "Padmanabha nagar": 564,
  Padmanabhanagar: 565,
  "Padmanabhanagar, Bengaluru, Karnataka, India": 566,
  "Pai Layout, Mahadevapura, Bengaluru, Karnataka, India": 567,
  "Pai Layout,Mahadevapura": 568,
  "Palace Guttahalli": 569,
  Pallavaram: 570,
  Panathur: 571,
  "Panchasheel Nagar": 572,
  "Pantarapalya,Nayanda Halli": 573,
  Pantharapalya: 574,
  Papareddipalya: 575,
  Parangipalya: 576,
  Pattanagere: 577,
  "Pattanagere,RR Nagar": 578,
  "Pattandur Agrahara": 579,
  "Pattandur Agrahara,Whitefield": 580,
  Pattegarhpalya: 581,
  "Phase 1,Doddanekkundi": 582,
  "Phase 1,Whitefield": 583,
  "Phase 2,Brookefield": 584,
  "Phase 4,JP Nagar": 585,
  "Poornaprajna Layout": 586,
  Prakashnagar: 587,
  "Prasanth Extension, Whitefield, Bengaluru, Karnataka, India": 588,
  "Prashant Nagar, Vijaya Nagar, Bengaluru, Karnataka, India": 589,
  "Prestige Ozone,Whitefield": 590,
  "Prestige Shantiniketan, Hoodi, Bengaluru, Karnataka, India": 591,
  "Pulikeshi Nagar": 592,
  "Pulkeshi Nagar": 593,
  "Purvankara Whitehall, Sarjapur Main Road, Harlur, Bengaluru, Karnataka, India": 594,
  "RK Mutt Rd, Gupta Layout, Ulsoor, Bengaluru, Karnataka 560008, India,Bengaluru": 595,
  "RPC Layout": 596,
  "RR Nagar": 597,
  "RR Nagar Arch, Kenchenhalli, Bengaluru, Karnataka, India": 598,
  "RR Nagar, Bengaluru, Karnataka, India": 599,
  "Ragavendra Layout, Nisarga Layout": 600,
  "Rainbow Drive,Halanayakanahalli": 601,
  "Raj Rajeswari Nagar BMTC Bus Depot, Raja Rajeshwari Nagar, Bengaluru, Karnataka, India": 602,
  "Raja Rajeshwari Nagar": 603,
  "Rajaji Nagar": 604,
  "Rajaji Nagar,": 605,
  "Rajaji Nagar, 2nd Block, Bengaluru, Karnataka, India": 606,
  "Rajaji Nagar, 2nd Stage": 607,
  "Rajaji Nagar, Bengaluru, Karnataka, India": 608,
  "Rajaji nagar": 609,
  RajajiNagar: 610,
  Rajajinagar: 611,
  "Rajarajeshwari Nagar": 612,
  Rajarajeshwarinagar: 613,
  Rajarajeswarinagar: 614,
  "Rajashree Layout, Gandhi Nagar": 615,
  Ramagondanahalli: 616,
  "Ramagondanahalli,Whitefield": 617,
  "Ramanashree Enclave,Bilekahalli": 618,
  "Ramesh Nagar": 619,
  "Raneem Nilayam, 5th B Cross Rd, HAL 2nd Stage, Kodihalli, Bengaluru, Karnataka 560008, India,Bengaluru": 620,
  "Ranganathan Colony": 621,
  "Ranka Colony,Bilekahalli": 622,
  "Rasanna Colony,Vibhutipura": 623,
  "Richmond Town": 624,
  "Roopena Agrahara": 625,
  "Roopena Agrahara, Bommanahalli": 626,
  "Roopena Agrahara,Bommanahalli": 627,
  "Rupena Agrahara": 628,
  "Rustam Bagh Layout": 629,
  "S.G. Palya": 630,
  "SAP Labs India Pvt. Ltd., KIADB Export Promotion Industrial Area, Whitefield, Bengaluru, Karnataka, India": 631,
  "SBM Colony": 632,
  "SRK Garden, Jayanagar": 633,
  Sadanandanagar: 634,
  "Sadanandanagar,Bennigana Halli": 635,
  "Sadaramangala,Krishnarajapura": 636,
  Samethanahalli: 637,
  "Sampangi Rama Nagar": 638,
  "Sampangi Rama Nagara": 639,
  "Sampige Layout": 640,
  "Sanjeevini Nagar": 641,
  "Sapna Book House, Michael Palaya, Indiranagar, Bengaluru, Karnataka, India": 642,
  Sarjapur: 643,
  "Sarjapur Main Road": 644,
  "Sarjapur Road": 645,
  "Sarjapur Road Post Railway Crossing": 646,
  "Sarjapur Road Till Wipro": 647,
  "Sarjapur Road Wipro To Railway Crossing": 648,
  "Sarjapur Road, Kaikondrahalli": 649,
  "Sector 1, HSR Layout": 650,
  "Sector 2, HSR Layout": 651,
  "Sector 2,HSR Layout": 652,
  "Sector 3, HSR Layout": 653,
  "Sector 4 HSR Layout": 654,
  "Sector 4,HSR Layout 5th Sector": 655,
  "Sector 6,HSR Layout": 656,
  "Sector 7, HSR Layout": 657,
  "Sector 7,HSR Layout": 658,
  "Seegehalli,Kadugodi": 659,
  "Seetarampalya, equal distance from Hoodi": 660,
  Seetharampalya: 661,
  "Seetharampalya,Hoodi": 662,
  "Seetharampalya,Whitefield": 663,
  Sevanagar: 664,
  "Shamana Garden,Wilson Garden": 665,
  Shankarapura: 666,
  "Shanti Nagar": 667,
  Sheshadripuram: 668,
  "Shirdi Sai Nagar,Munnekollal": 669,
  "Shivaji Nagar": 670,
  "Shubh Enclave, Harlur, Bengaluru, Karnataka, India": 671,
  Siddapura: 672,
  "Siddapura, Bengaluru, Karnataka, India": 673,
  "Siddapura,Whitefield": 674,
  "Silver Springs Layout,Marathahalli": 675,
  "Silver Springs Layout,Munnekollal": 676,
  "Sindhi Colony,Pulikeshi Nagar": 677,
  "Sobha Dream Acres, Balagere Road, Varthur, Bengaluru, Karnataka, India": 678,
  "Somasundara Palya": 679,
  "Someshwara Layout,Doddakannelli": 680,
  "Someshwara Nagar": 681,
  Sorahunase: 682,
  "Spoorthi Sahithya Apartment Mahadevapura": 683,
  "Sri Jnanakshi Vidyaniketan, Kenchena Halli Rd, Halagevaderahalli, Rajarajeshwarinagar, Bengaluru, Karnataka, India": 684,
  "Sri Krishna Garden Layout,RR Nagar": 685,
  "Sri Lorven Homes, Kondappa Layout, Vignan Nagar, Viswajeeth Layout, Doddanekkundi, Bengaluru, Karnataka 560075": 686,
  "Sri Sai Baba Ashram, Kadugodi white field": 687,
  Srinagar: 688,
  Srinivapura: 689,
  "Srinivasanagara, Banashankari Stage I": 690,
  Srinivasnagar: 691,
  Srinivaspura: 692,
  Srirampura: 693,
  Srirampuram: 694,
  "Stage 2, BTM Layout": 695,
  "Stage 2,BTM 2nd Stage": 696,
  "Stage 2,BTM Layout": 697,
  Subramanyapura: 698,
  Suddaguntapalya: 699,
  "Suddaguntapalya,C V Raman Nagar": 700,
  "Suddagunte Palya": 701,
  "Suddagunte Palya,": 702,
  "Sudhama Nagar": 703,
  "Suncity Gloria Apartments, Sarjapur Main Road, Opp. to Decathlon Sports, Carmelaram, Ambedkar Nagar, Chikkabellandur, Carmelaram, Ambedkar Nagar, Chikkabellandur, Bengaluru, Karnataka 560035, India": 704,
  Sunkadakatte: 705,
  "Swami Vivekananda Road, Upkar Layout, Whitefield": 706,
  "Talacauvery Layout": 707,
  "Tasker Town": 708,
  "Tata Silk Farm,Jayanagar": 709,
  Tavarekere: 710,
  "Tavarekere, Ramappa layout, 1st Stage, BTM Layout, Bengaluru, Karnataka, India": 711,
  "Tavarekere, Suddagunte Palya": 712,
  "Tavarekere,BTM Layout": 713,
  "Thigalarapalya,Hoodi": 714,
  Thippasandra: 715,
  Thirumalashettyhally: 716,
  Thubarahalli: 717,
  "Thubarahalli,Brookefield": 718,
  "Thubarahalli,Munnekollal": 719,
  "Thubarahalli,Whitefield": 720,
  "Thubarahalli.": 721,
  "Thyagaraja Nagar": 722,
  "Tigalarpalya,Brookefield": 723,
  "Tilak Nagar": 724,
  "Tin Factory": 725,
  Tippasandra: 726,
  Tubarahalli: 727,
  "Tyagaraja Nagar": 728,
  "Udaya Nagar": 729,
  "Udaya Nagar,Mahadevapura": 730,
  Ulsoor: 731,
  Uttarahalli: 732,
  "Uttarahalli Bus Stand, Subramanyapura Main Rd, Friends Colony, Uttarahalli Hobli, Bengaluru, Karnataka 560061, India": 733,
  "Uttarahalli Hobli": 734,
  "Uttarahalli Hobli Stage 2": 735,
  "Uttarahalli Road": 736,
  Uttarahallli: 737,
  "VV Giri Colony,Sheshadripuram": 738,
  "VV Puram": 739,
  Valepura: 740,
  "Valliyamma Layout,Kaikondrahalli": 741,
  Varadharajapuram: 742,
  "Varsova Layout,Kaggadasapura": 743,
  Varthur: 744,
  "Varthur Balagere": 745,
  "Varthur Kodi": 746,
  "Vasanth Nagar": 747,
  "Vasanth Nagar,": 748,
  "Vasantha Nagara": 749,
  "Veerabhadra Nagar": 750,
  "Venkappa Garden,Koramangala": 751,
  Venkatapura: 752,
  "Venkateshwara Layout": 753,
  Vibhutipura: 754,
  "Victoria Layout": 755,
  "Victoria Layout,": 756,
  "Vidyapeeta Layout, Banashankari, Bengaluru, Karnataka, India": 757,
  "Vignan Nagar": 758,
  "Vijay Nagar": 759,
  "Vijay Nagar, Whitefield": 760,
  "Vijay Nagar,Whitefield": 761,
  "Vijaya Nagar": 762,
  Vijayanagar: 763,
  "Vijayanagar Metro Station, Chord Road, Vijaya Nagar, Bengaluru, Karnataka, India": 764,
  Vijaynagar: 765,
  Vimanapura: 766,
  "Vinayak Nagar, Vinayaka Nagar, Murgesh Pallya, Bengaluru, Karnataka, India": 767,
  "Vinayaka Nagar": 768,
  "Virat Nagar": 769,
  Vishweshwarapura: 770,
  "Vittal Nagar": 771,
  "Viveka Nagar": 772,
  "West Tambaram, Tambaram": 773,
  "West of Chord Road": 774,
  Whitefield: 775,
  "Whitefield Hope Farm Junction": 776,
  "Whitefield, Bengaluru, Karnataka, India": 777,
  "Wilson Garden": 778,
  "Xavier Layout": 779,
  "Yamalur,HAL": 780,
  Yelachenahallli: 781,
  "Yelachenahallli,Kumaraswamy Layout": 782,
  Yemalur: 783,
  "Yemalur Main Road, Kempapura, Bellandur, Bengaluru, Karnataka, India": 784,
  "Yemalur,Bellandur": 785,
  "d block AECS Layout, Bengaluru, Karnataka, India": 786,
  "jagadish nagar , Kaggadasapura": 787,
  kaikondrahalli: 788,
  mesjestic: 789,
  "uUlsoor, Bengaluru, Karnataka, India": 790,
  whitefield: 791,
};

export const typesMapping = {
  BHK2: 1,
  BHK1: 0,
  BHK3: 2,
  RK1: 5,
  BHK4: 3,
  BHK4PLUS: 4,
};
